/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: shouryahaldkar (https://sketchfab.com/shouryahaldkar)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hero-character-756a2b3ceeda4190870f6bd860bca5cb
title: Hero character
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/personaje.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.war2txt_alucard03_d}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.war2txt_alucard03_d1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/personaje.gltf");
